#Tomcat Embedded Server Configuration
server:
  port: 8282

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE
      routes:
        - id: ms-medicamento
          uri: http://localhost:8080/
          predicates:
            - Path=/api/medicamentos/**
        - id: ms-venta
          uri: http://localhost:8081/
          predicates:
            - Path=/venta/ventas/**

 
#Eureka Configuration Properties
eureka: 
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

